import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Instagram, Facebook, Mail, YoutubeIcon } from "lucide-react";
import profileImage from "../assets/stephan1.png";
const Hero = () => {
    return (_jsxs("div", { className: "relative w-full min-h-screen bg-transparent overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 flex justify-center items-start", children: _jsx("img", { src: profileImage, alt: "St\u00E9phanie", className: "\r\n            w-full h-full object-cover\r\n            transition-transform duration-500\r\n            hover:scale-105\r\n            shadow-xl\r\n          ", style: {
                        objectPosition: "center 20%", // Ajuste pour bien voir le visage
                        marginTop: 0
                    } }) }), _jsxs("div", { className: "relative z-10 flex flex-col justify-between min-h-screen px-6 md:px-20 py-10 pt-24", children: [_jsx("div", { className: "min-h-screen flex items-center justify-center ", children: _jsxs("div", { className: "max-w-xl space-y-6 bg-white/1 rounded-lg p-6 shadow-lg", children: [_jsx("h2", { className: "text-lg text-gray-600 tracking-wide", children: "Enchant\u00E9e, je suis" }), _jsx("h1", { className: "text-5xl md:text-6xl font-extrabold text-blue-600 leading-tight drop-shadow-sm", children: "St\u00E9phanie.B" }), _jsxs("p", { className: "text-gray-700 text-lg leading-relaxed font-medium", children: ["Directrice G\u00E9n\u00E9rale Adjointe chez", " ", _jsx("span", { className: "font-semibold text-blue-700", children: "RENAPROV Finance S.A" }), ",", _jsx("br", {}), "cr\u00E9atrice de contenu et entrepreneure."] })] }) }), _jsx("footer", { className: "mt-20", children: _jsxs("div", { className: "flex flex-col md:flex-row md:justify-between items-center gap-6 pt-6", children: [_jsxs("div", { className: "flex gap-6", children: [_jsx("a", { href: "https://www.instagram.com/stephy_bissai?igsh=MWExNTVtYTEwejIwbw==", "aria-label": "Instagram", children: _jsx(Instagram, { size: 24, className: "text-gray-1000 hover:text-pink-500 transition" }) }), _jsx("a", { href: "#", "aria-label": "Mail", children: _jsx(Mail, { size: 24, className: "text-gray-1000 hover:text-blue-500 transition" }) }), _jsx("a", { href: "https://www.facebook.com/profile.php?id=61573837800433&__tn__=-UC*F", "aria-label": "Facebook", children: _jsx(Facebook, { size: 24, className: "text-gray-1000 hover:text-blue-700 transition" }) }), _jsx("a", { href: "http://www.youtube.com/@MarcherAvecChrist", "aria-label": "YouTube", children: _jsx(YoutubeIcon, { size: 24, className: "text-gray-1000 hover:text-red-600 transition" }) })] }), _jsx("p", { className: "text-sm text-gray-1000 text-center md:text-right", children: "\u00A9 2025 St\u00E9phanie.B \u2013 Tous droits r\u00E9serv\u00E9s" })] }) })] })] }));
};
export default Hero;
